### ISSUE TITLE
S1-S2

### ISSUE THREAD

**Issue by npherrm** [rer145/ta3#57]
S1-S2 fusion
![image](https://user-images.githubusercontent.com/28597646/133282834-7e94ba0e-9c2e-4d7f-8f5e-8d7bb6dd0ba8.png)
The coding for S1-S2 fusion sequences incorrectly with >10mm coding as 1 and <10mm coding a 0 - These should be flipped.

**Comment by rer145** [comment]
Hi Nick,

This issue has been fixed in the newest version of TA3, version 0.8.5. You can download this version here:  https://github.com/rer145/ta3/releases/tag/v0.8.5

Once you download and run the application, go to the Help menu and choose "Check for Asset Updates". This will check to make sure you have the latest versions of all the assets and download them for you. This new version of the app includes this asset updater and the fix for this issue is included in an updated asset file.

Please let me know if you have any other issues.
